# Generated by Django 5.1.7 on 2025-03-21 23:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='template_variables',
            field=models.JSONField(blank=True, help_text='JSON specification of variables used in template', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('consent_form', 'Consent Form'), ('dpa', 'Data Processing Agreement'), ('dpia', 'Data Protection Impact Assessment'), ('record_processing', 'Record of Processing Activities'), ('breach_notification', 'Breach Notification Template'), ('subject_access_response', 'Subject Access Request Response'), ('erasure_confirmation', 'Right to Erasure Confirmation'), ('data_portability', 'Data Portability Export'), ('other', 'Other Document')], max_length=100),
        ),
        migrations.CreateModel(
            name='DataSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('marketing_consent_date', models.DateTimeField(blank=True, null=True)),
                ('data_processing_consent', models.BooleanField(default=False)),
                ('data_processing_consent_date', models.DateTimeField(blank=True, null=True)),
                ('cookie_consent', models.BooleanField(default=False)),
                ('cookie_consent_date', models.DateTimeField(blank=True, null=True)),
                ('data_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('privacy_notice_version', models.CharField(blank=True, max_length=20)),
                ('privacy_notice_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_subjects', to='api.organization')),
            ],
            options={
                'verbose_name_plural': 'Data Subjects',
                'unique_together': {('organization', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ConsentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('consent_given', 'Consent Given'), ('consent_withdrawn', 'Consent Withdrawn'), ('privacy_notice_viewed', 'Privacy Notice Viewed'), ('privacy_notice_accepted', 'Privacy Notice Accepted'), ('data_accessed', 'Data Accessed'), ('data_updated', 'Data Updated'), ('data_deleted', 'Data Deleted')], max_length=100)),
                ('consent_type', models.CharField(blank=True, choices=[('marketing', 'Marketing'), ('data_processing', 'Data Processing'), ('cookies', 'Cookies'), ('other', 'Other')], max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('data_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_activities', to='api.datasubject')),
            ],
            options={
                'verbose_name_plural': 'Consent Activities',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='data_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='api.datasubject'),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL)),
                ('data_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='api.datasubject')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='api.organization')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='api.datasubjectrequest')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('collect_information', 'Collect Information'), ('verify_identity', 'Verify Identity'), ('search_data', 'Search for Data'), ('generate_document', 'Generate Document'), ('send_notification', 'Send Notification'), ('approval', 'Approval Step'), ('data_action', 'Data Action (e.g., deletion)'), ('custom', 'Custom Step')], max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_automated', models.BooleanField(default=False)),
                ('automation_script', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('result_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to=settings.AUTH_USER_MODEL)),
                ('document_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='api.document')),
                ('generated_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_from_steps', to='api.document')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.workflowinstance')),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_workflows', to='api.workflowstep'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('subject_access', 'Subject Access Request'), ('erasure', 'Right to Erasure'), ('rectification', 'Data Rectification'), ('breach_notification', 'Data Breach Notification'), ('consent_withdrawal', 'Consent Withdrawal'), ('custom', 'Custom Workflow')], max_length=100)),
                ('estimated_completion_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('collect_information', 'Collect Information'), ('verify_identity', 'Verify Identity'), ('search_data', 'Search for Data'), ('generate_document', 'Generate Document'), ('send_notification', 'Send Notification'), ('approval', 'Approval Step'), ('data_action', 'Data Action (e.g., deletion)'), ('custom', 'Custom Step')], max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_automated', models.BooleanField(default=False)),
                ('automation_script', models.TextField(blank=True, help_text='Python script for automation if applicable')),
                ('estimated_duration_hours', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_template', models.ForeignKey(blank=True, help_text='Document template to use if this step generates a document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_templates', to='api.document')),
                ('workflow_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='api.workflowtemplate')),
            ],
            options={
                'ordering': ['workflow_template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='api.workflowtemplate'),
        ),
    ]
